# Generated by Django 6.0 on 2025-12-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tanggal_lahir',
            field=models.DateField(blank=True, help_text='Format: YYYY-MM-DD', null=True),
        ),
    ]
